lsi: false
live: true
url: https://davetayls.me
permalink: /blog/:year/:month/:day/:title
postimage_default: /content/placeholder.jpg
site_name: Dave Taylor
years_experience: 15
job_title: Tech Lead, Consultant, Mentor
job_description: Frontend leadership, Frontend architecture, HTML(5), JavaScript (OOJS, ES6, TypeScript), CSS (BEM, Less, SASS, Stylus), Testable Code (Mocha, Sinon, Chai, Karma), NodeJs (Express, Mongoose) , Cloud Applications (Heroku, S3, Azure)
keywords: Dave Taylor, David Taylor, Frontend leadership, Frontend architecture, HTML(5), JavaScript (OOJS, ES6, TypeScript), CSS (BEM, Less, SASS, Stylus), Testable Code (Mocha, Sinon, Chai, Karma), NodeJs (Express, Mongoose) , Cloud Applications (Heroku, S3, Azure)
mission:
  I believe in community, in inspiration and creativity.
  I believe it's an inspired team and a laser focus on the user's experiece that will produce the best results.
  I want to help frontend teams live inspired, be productive and scale better.
exclude:
- startjekyll.bat
- .idea
- node_modules
- package.json
- typings
- src
