lsi: false
live: true
permalink: /blog/:year/:month/:day/:title
postimage_default: /content/placeholder.jpg
job_title: Frontend Developer, Consultant, Mentor
job_description: Frontend leadership, Frontend architecture, HTML(5), JavaScript (OOJS, ES6, TypeScript), CSS (BEM, Less, SASS, Stylus), Testable Code (Mocha, Sinon, Chai, Karma), NodeJs (Express, Mongoose) , Cloud Applications (Heroku, S3, Azure)
mission: I'm an experienced Frontend Consultant and HTML5 App Developer. He wants to help frontend teams live inspired, be productive and scale better.
exclude:
- startjekyll.bat
- node_modules
- package.json
- typings
- src
