
- name: Senior HTML5 Development
  pitch: I'll build your product! I can join your team and get stuck in
  quote: 1
  about: >
    I love the process of building great products. The reason I've kept my passion
    for frontend builds over the last 14 years is because I believe that together
    we can excite and delight the people using what we've created.


    I can work on-site in Bath or remotely from my office if you're based in
    London or elsewhere in the UK with regular on-site visits dependent on your location.


    I'm happy to come and meet you to discuss your project, give me a call and we can
    arrange a good time.


    My skills include: Frontend architecture, **HTML5**, **JavaScript** (OOJS, ES6, TypeScript),
    **CSS** (BEM, Less, SASS, Stylus), **Testable Code** (Mocha, Sinon, Chai, Karma), **NodeJs** (Express, Mongoose),
    **Cloud Applications** (Heroku, S3, Azure).


    I've built highly performant HTML5 cross platform applications for browsers and Cordova:
    **Canvas** and image manipulation, **Backbone**, **React** Native.
  rewards:
    - I will set good foundations to your frontend build
    - I will use my 14 years of experience
    - I will give a boost to your team's productivity

- name: Lead Frontend Development and Architecture
  pitch: I will lead a team, set architecture and make sure they are working at their best
  quote: 3
  about: >
    I have designed the frontend architecture of many large websites and HTML5 apps.
    These have included:

     - enterprise CMS builds for Lloyd's of London, British Red Cross and Arrow Electronics
     - campaign sites for The FA and RFU;

    I take a modular approach and work closely with designers as well as developers
    to achieve scaleable results.


    I am keen to marry good inter-personal and communication skills with solid technical
    thought leadership enabling teams to grow in confidence and produce great work.

  rewards:
    - I base my decisions on tried-and-tested solutions
    - I analyse and make the most of current trends
    - I am experienced at communicating and leading teams

- name: Frontend Consultancy and Mentoring
  pitch: I'll help you build a lasting culture of innovation and creativity
  quote: 4
  about: >
    I want to see every frontend developer live inspired and creative. I believe
    we all have a child's passion inside of us which wants to do great things.


    I'm so grateful to have had the opportunity of unlocking this passion
    and to see groups of people tackle a project head on and become a team.


    I like to work closely with the project leads to really get to know each
    member of the team, put in place a pathway for them to grow technically
    and to gain the confidence to lead others.


    Ultimately I have two aims:


    1. To inspire the team and provide them with the skills they need to
       build great products

    2. To find and nurture emerging leaders to continue this work with
       those more junior than they are
  rewards:
    - I encourage and guide emerging leaders within your team
    - I build a plan to level up frontend developer's skills
    - I focus the team on building a great product experience
